### PR TITLE
Youtube Video Player Page

### PR DESCRIPTION
**Pull request by kiptubei**
This project is the first one we are submitting for review.  It is a simple youtube video player, made with Html and CSS purely. The submission consists of;

**- The Navigation Bar

- The Video Section Part

- Suggested Video Part

- Comment Section and lastly,

- The Footer Section.**

We have made the corrections the TSE pointed out, which includes;

- The deletion of all comments presents in the Html and CSS file.

- Deletion of the 70% width limitation.

- Addition of a live link to the Readme file.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Nice Job Team 👏👏👏

This looks great @kiptubei  and @haraphat01.

Particularly love the fact that you used the archived webpage link in making your clone as described in the Microverse Adjustments section. That shows you pay attention to details.👍

However, there are a few requirements that need to be met before proceeding👇:

- [ ] Kindly edit your pull request, and make a more descriptive Pull Request message-give it a descriptive name that shortly says what this branch includes. Refer to [screenshot](https://user-images.githubusercontent.com/33323077/77903174-5a03da80-727a-11ea-8259-b76c0d84d303.png)
 from [Partwright].

- [ ] There are errors in your HTML file. Please ensure you use this validator [tool](https://validator.w3.org/nu/) to check for errors and fix them.

- [ ] Also please remove all comments on your HTML and CSS files. t’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
ice_screenshot_20200330-102340

- [ ] Kindly add a margin between the aside section to the right of your page This is yours👇[Screenshot]
inked1

**But this is the way it should look 👇[Screenshot]**
ice_screenshot_20200330-103948

- [ ] Remove the spacing that exists between the sidebar videos and the video text 👇{Screenshot]
inked2

- [ ] Add a choose language template on your webpage as can be seen in the original webpage 👇[Screenshot]
ice_screenshot_20200330-103926

- [x] Kindly remove the left and right margins that exist to the side of the webpage. 👇[Screenshot]
inked4

- [ ]  Also on the original webpage there is an `Autoplay` text, with a toggle icon beside it, consider adding it too 👇[Screenshot]
inked3

- [ ] Kindly make changes to the footer section of your page to reflect the original webpage; include the font-size of the footer links and create a space between the footer and the edges of the page, also add a space between the footer and the edges of the page. 
**This is yours👇[Screenshot]**
ice_screenshot_20200330-102340

**This is the way it should be👇[Screenshot]**
ice_screenshot_20200330-103817

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**Once more good job for a first project**👏

HAPPY CODING👨‍💻

**Comment by kiptubei** [comment]
Hello mikenath, we have made the changes requested however ,there is one issue that we request a review on ,specifically:

 Kindly remove the left and right margins that exist to the side of the webpage. point_down[Screenshot] (https://user-images.githubusercontent.com/33323077/77901314-4c992100-7277-11ea-8950-d64a4c2026f8.jpg)

we designed the page with this [site](http://archive.vn/Bss88) as our source page as instructed in the project description. As such a change such as that would require us to re-style the entire page.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Good job @kiptubei  and @haraphat01 👍👍

It's nice that you made some fixes to your project.👍

However, kindly fix this issues:

- [ ] Required - As referenced in the previous review, kindly delete all comments on your HTML and CSS.

- [ ] Required - The web archive link shows a screenshot of the page, it not necessary to add left and right margins to your page as this is not part of the webpage. Kindly remove the margins(To do this remove the 70% width set to the div with class name outer-div). Then fix issues that result from this.

- [ ] Required - I sincerely apologize that this wasn't referenced in the previous review - Kindly add a live version link to your readme, Use this [tool](https://raw.githack.com/) to do that. Simply paste your repo link there and copy one of the two links generated.

**- [ ] Required - Also as referenced in the previous review remove the margin that exists between the sidebar video and the sidebar text. [Screenshot]👇**
ice_screenshot_20200331-111111


**- [ ] Required - Also add a margin between the main content and the sidebar content.**
ice_screenshot_20200331-111124

I trust you will carry out these changes.👍💪

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Nice Job Team 👍👍

You did quite well on this project. 🎉
Good job adding a live link to the readme and adding the recommended sections to the project.
You've come quite a long away from the first review.👍

However, there are still a few changes to be made.

**Kindly hang in there, you've got this💪👌**

Please make the following changes:

- [ ] Required - The video section of the page almost completely overlaps the sidebar video. Please fix this overlap issue.👇
ice_screenshot_20200401-013558

- [ ] Required - The choose your language section looks quite different from the original webpage.

**THIS IS YOURS**👇
ice_screenshot_20200401-013845

**THIS IS THE WAY IT SHOULD BE👇**
ice_screenshot_20200401-015216

- [ ] Required - Also the subscribe section just below the video section looks different than the original. Kindly fix it.

**THIS IS YOURS👇**
ice_screenshot_20200401-013917

**THIS IS THE WAY IT SHOULD BE👇**
ice_screenshot_20200401-015234

- [ ] Required - The footer section of your page particularly the logo section is overlapping a footer content. Kindly correct it. Also, add a padding between the footer content and the sides of the page.

**THIS IS YOURS**👇
ice_screenshot_20200401-013950

**THIS IS THE WAY IT SHOULD BE**👇
ice_screenshot_20200401-015311

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING AND WELCOME TO MICROVERSE!👨‍💻🎉

**Comment by mikenath223** [comment]
Also, kindly fix the merge conflicts with the base branch👆. The conflicting file appears to be your readMe.👍

**Comment by kiptubei** [comment]
Hello Michhgolden,
 I found that the reason why the files were overlapping is that the styling had been done on a zoom of 70%  on chrome thus when viewed on the default zoom of 100% on firefox or raw githack the elements lost their formation. We have re-styled and made the site a bit  more responsive on a greater number of browsers and on the deafualt zoom.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### Good work you have put in :clap: However, you have a few fixes to make before your project could be approved.
- Also, kindly fix the merge conflicts with the base branchpoint_up_2. The conflicting file appears to be your readMe.+1
- Remove the horizontal scroll on your page
- Your featured video should take the full width of the div
youtube video
### Make these changes and resubmit another code review. Good luck.
- happy coding!

**Comment by uryelah** [comment]
Hello **Arafat Akata** & **Mark Kiptubei**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all good job with fixing most of the issues with the clone and submitting your first Microverse project🌟**

Since the project went through a lot of reviews already and it's the first HTML project I'll approve it. But next project please make sure to read carefully each pointer that a TSE gives you. 

------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

### Optional Improvements

- [OPTIONAL] Add the margin between the video thumbnail and its title for each recommended video in the right.

- [OPTIONAL] Use the `aside` tag for the videos in the right. Currently, they are inside the `sidebar_side.div`. Read more on semantic [HTML here.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside)

- [OPTIONAL] The logo used has a low resolution, looks pixelated. When you need a logo don't take screenshots from the original site, you can inspect the original site and get the `svg` image they use or look on google images for the logo, it can be a png image with transparent background or an svg.
The awesome thing about svg is that it's just code that you can copy and paste, it's easy to change the colors, and it scales well to any size you need it to be, unlike normal images that get distorted.
[Read more on svg images here,](https://deliciousbrains.com/svg-advantages-developers/)
----

**Keep being an awesome dev and good luck with your next project!**


Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
